import tailwindcssAnimate from 'tailwindcss-animate'
import typography from '@tailwindcss/typography'
import containerQueries from '@tailwindcss/container-queries'

/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  darkMode: ['selector', '[data-theme="dark"]'],
  plugins: [tailwindcssAnimate, typography, containerQueries],
  prefix: '',
  safelist: [
    'lg:col-span-4',
    'lg:col-span-6',
    'lg:col-span-8',
    'lg:col-span-12',
    'border-border',
    'bg-card',
    'border-error',
    'bg-error/30',
    'border-success',
    'bg-success/30',
    'border-warning',
    'bg-warning/30',
    // Typography classes for responsive scaling
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-4xl',
    'text-5xl',
    'text-6xl',
    'text-7xl',
    'text-8xl',
    'text-9xl',
    'sm:text-xs',
    'sm:text-sm',
    'sm:text-base',
    'sm:text-lg',
    'sm:text-xl',
    'sm:text-2xl',
    'sm:text-3xl',
    'sm:text-4xl',
    'sm:text-5xl',
    'sm:text-6xl',
    'sm:text-7xl',
    'sm:text-8xl',
    'sm:text-9xl',
    'lg:text-xs',
    'lg:text-sm',
    'lg:text-base',
    'lg:text-lg',
    'lg:text-xl',
    'lg:text-2xl',
    'lg:text-3xl',
    'lg:text-4xl',
    'lg:text-5xl',
    'lg:text-6xl',
    'lg:text-7xl',
    'lg:text-8xl',
    'lg:text-9xl',
    // Line height classes
    'leading-none',
    'leading-tight',
    'leading-snug',
    'leading-normal',
    'leading-relaxed',
    'leading-loose',
    'sm:leading-none',
    'sm:leading-tight',
    'sm:leading-snug',
    'sm:leading-normal',
    'sm:leading-relaxed',
    'sm:leading-loose',
    'lg:leading-none',
    'lg:leading-tight',
    'lg:leading-snug',
    'lg:leading-normal',
    'lg:leading-relaxed',
    'lg:leading-loose',
    // Font weight classes
    'font-thin',
    'font-light',
    'font-normal',
    'font-medium',
    'font-semibold',
    'font-bold',
    'font-extrabold',
    'font-black',
    'sm:font-thin',
    'sm:font-light',
    'sm:font-normal',
    'sm:font-medium',
    'sm:font-semibold',
    'sm:font-bold',
    'sm:font-extrabold',
    'sm:font-black',
    'lg:font-thin',
    'lg:font-light',
    'lg:font-normal',
    'lg:font-medium',
    'lg:font-semibold',
    'lg:font-bold',
    'lg:font-extrabold',
    'lg:font-black',
    // Letter spacing classes
    'tracking-tighter',
    'tracking-tight',
    'tracking-normal',
    'tracking-wide',
    'tracking-wider',
    'tracking-widest',
    'sm:tracking-tighter',
    'sm:tracking-tight',
    'sm:tracking-normal',
    'sm:tracking-wide',
    'sm:tracking-wider',
    'sm:tracking-widest',
    'lg:tracking-tighter',
    'lg:tracking-tight',
    'lg:tracking-normal',
    'lg:tracking-wide',
    'lg:tracking-wider',
    'lg:tracking-widest',
  ],
  theme: {
    container: {
      center: true,
      padding: {
        '2xl': '2rem',
        DEFAULT: '1rem',
        lg: '2rem',
        md: '2rem',
        sm: '1rem',
        xl: '2rem',
      },
      screens: {
        '2xl': '86rem',
        lg: '64rem',
        md: '48rem',
        sm: '40rem',
        xl: '80rem',
      },
    },
    extend: {
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      // Container query configuration
      containers: {
        richtext: '100%',
        'richtext-narrow': '300px',
        'richtext-compact': '400px',
        'richtext-comfortable': '600px',
        'richtext-spacious': '800px',
        'richtext-wide': '1000px',
        block: '100%',
        'block-xs': '200px',
        'block-sm': '300px',
        'block-md': '400px',
        'block-lg': '600px',
        'block-xl': '800px',
        media: '100%',
        'media-sm': '300px',
        'media-md': '600px',
        'media-lg': '900px',
      },
      colors: {
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        background: 'hsl(var(--background))',
        border: 'hsla(var(--border))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        foreground: 'hsl(var(--foreground))',
        input: 'hsl(var(--input))',
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        ring: 'hsl(var(--ring))',
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        success: 'hsl(var(--success))',
        error: 'hsl(var(--error))',
        warning: 'hsl(var(--warning))',

        // Custom colors
        'brand-primary': 'var(--brand-primary)',
      },
      fontFamily: {
        mono: ['var(--font-geist-mono)'],
        sans: ['var(--font-geist-sans)'],
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      typography: () => ({
        DEFAULT: {
          css: [
            {
              '--tw-prose-body': 'var(--text)',
              '--tw-prose-headings': 'var(--text)',
              h1: {
                fontWeight: 'normal',
                marginBottom: '0.25em',
              },
            },
          ],
        },
        // Mobile-first typography scales
        xs: {
          css: [
            {
              fontSize: '0.75rem',
              lineHeight: '1.5',
              h1: { fontSize: '1.5rem', lineHeight: '1.25' },
              h2: { fontSize: '1.25rem', lineHeight: '1.25' },
              h3: { fontSize: '1.125rem', lineHeight: '1.375' },
              h4: { fontSize: '1rem', lineHeight: '1.375' },
              p: { fontSize: '0.875rem', lineHeight: '1.625' },
            },
          ],
        },
        sm: {
          css: [
            {
              fontSize: '0.875rem',
              lineHeight: '1.625',
              h1: { fontSize: '1.875rem', lineHeight: '1.25' },
              h2: { fontSize: '1.5rem', lineHeight: '1.25' },
              h3: { fontSize: '1.25rem', lineHeight: '1.375' },
              h4: { fontSize: '1.125rem', lineHeight: '1.375' },
              p: { fontSize: '0.875rem', lineHeight: '1.625' },
            },
          ],
        },
        base: {
          css: [
            {
              fontSize: '1rem',
              lineHeight: '1.625',
              h1: { fontSize: '2.25rem', lineHeight: '1.25' },
              h2: { fontSize: '1.875rem', lineHeight: '1.25' },
              h3: { fontSize: '1.5rem', lineHeight: '1.375' },
              h4: { fontSize: '1.25rem', lineHeight: '1.375' },
              p: { fontSize: '1rem', lineHeight: '1.625' },
            },
          ],
        },
        lg: {
          css: [
            {
              fontSize: '1.125rem',
              lineHeight: '1.625',
              h1: { fontSize: '3rem', lineHeight: '1.25' },
              h2: { fontSize: '2.25rem', lineHeight: '1.25' },
              h3: { fontSize: '1.875rem', lineHeight: '1.375' },
              h4: { fontSize: '1.5rem', lineHeight: '1.375' },
              p: { fontSize: '1.125rem', lineHeight: '1.625' },
            },
          ],
        },
        xl: {
          css: [
            {
              fontSize: '1.25rem',
              lineHeight: '1.625',
              h1: { fontSize: '3.75rem', lineHeight: '1.25' },
              h2: { fontSize: '3rem', lineHeight: '1.25' },
              h3: { fontSize: '2.25rem', lineHeight: '1.375' },
              h4: { fontSize: '1.875rem', lineHeight: '1.375' },
              p: { fontSize: '1.25rem', lineHeight: '1.625' },
            },
          ],
        },
        '2xl': {
          css: [
            {
              fontSize: '1.5rem',
              lineHeight: '1.625',
              h1: { fontSize: '4.5rem', lineHeight: '1.25' },
              h2: { fontSize: '3.75rem', lineHeight: '1.25' },
              h3: { fontSize: '3rem', lineHeight: '1.375' },
              h4: { fontSize: '2.25rem', lineHeight: '1.375' },
              p: { fontSize: '1.5rem', lineHeight: '1.625' },
            },
          ],
        },
      }),
    },
  },
}

export default config
