import type { Field } from 'payload'
import { validateSlugFormat } from '@/utilities/slugGeneration'

/**
 * Options for creating a slug field
 */
export interface SlugFieldOptions {
  /** Description to show in admin UI */
  description?: string
  /** Whether the slug is required (default: false) */
  required?: boolean
  /** Whether to show in sidebar (default: true) */
  sidebar?: boolean
}

/**
 * Factory function to create a standardized slug field configuration
 *
 * This creates a slug field with:
 * - Unique constraint
 * - Database index for fast lookups
 * - Format validation
 * - Consistent admin UI configuration
 * - Maximum length of 100 characters
 *
 * The slug is typically auto-generated by createSlugGenerationHook,
 * but can also be manually provided by users.
 *
 * @param options - Configuration options for the slug field
 * @returns A Payload field configuration
 *
 * @example
 * ```typescript
 * export const Posts: CollectionConfig = {
 *   slug: 'posts',
 *   fields: [
 *     { name: 'title', type: 'text', required: true },
 *     createSlugField({
 *       description: 'URL-friendly identifier (auto-generated from title)',
 *     }),
 *   ],
 * }
 * ```
 */
export const createSlugField = (options: SlugFieldOptions = {}): Field => {
  const { description, required = false, sidebar = true } = options

  return {
    name: 'slug',
    type: 'text',
    unique: true,
    index: true,
    required,
    maxLength: 100,
    admin: {
      position: sidebar ? 'sidebar' : undefined,
      description:
        description || 'URL-friendly identifier (auto-generated from title if not provided)',
    },
    validate: (value: string | null | undefined) => {
      // Allow empty values if not required (let required validation handle it)
      if (!value) {
        return true
      }

      // Validate slug format
      const validation = validateSlugFormat(value)
      if (!validation.isValid) {
        return validation.errors.join(', ')
      }

      return true
    },
  }
}

/**
 * Create a slug field with custom validation
 *
 * This variant allows you to add additional validation logic
 * on top of the standard format validation.
 *
 * @param options - Configuration options
 * @param customValidate - Additional validation function
 * @returns A Payload field configuration
 *
 * @example
 * ```typescript
 * createSlugFieldWithValidation(
 *   { required: true },
 *   async (value, { req }) => {
 *     // Custom validation logic
 *     if (value === 'forbidden') {
 *       return 'This slug is not allowed'
 *     }
 *     return true
 *   }
 * )
 * ```
 */
export const createSlugFieldWithValidation = (
  options: SlugFieldOptions = {},
  customValidate: (value: string, args: any) => boolean | string | Promise<boolean | string>,
): Field => {
  const baseField = createSlugField(options) as any

  return {
    ...baseField,
    validate: async (value: string | null | undefined, args: any) => {
      // Run base validation first
      if (!value) {
        return true
      }

      const baseValidation = validateSlugFormat(value)
      if (!baseValidation.isValid) {
        return baseValidation.errors.join(', ')
      }

      // Run custom validation
      return await customValidate(value, args)
    },
  } as Field
}
