export { HeroBlock } from './Hero/config'
export { ContentBlock } from './Content/config'
export { CallToActionBlock } from './CallToAction/config'
export { MediaBlock } from './MediaBlock/config'
export { ArchiveBlock } from './Archive/config'
export { Banner } from './Banner/config'
export { Code } from './Code/config'
