/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'social-media': SocialMedia;
    pages: Page;
    analyticsData: AnalyticsDatum;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'social-media': SocialMediaSelect<false> | SocialMediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    analyticsData: AnalyticsDataSelect<false> | AnalyticsDataSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    contact: ContactInformation;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Manage user accounts and permissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  roles: ('super-admin' | 'admin' | 'editor' | 'author' | 'user')[];
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Manage images, videos, and other media files
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text is required for accessibility compliance
   */
  alt: string;
  /**
   * Optional caption for the media
   */
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Click to set the focal point for responsive cropping
   *
   * @minItems 2
   * @maxItems 2
   */
  focalPoint?: [number, number] | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Manage social media links as global assets
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-media".
 */
export interface SocialMedia {
  id: number;
  /**
   * Social media platform
   */
  platform:
    | 'Facebook'
    | 'Twitter/X'
    | 'LinkedIn'
    | 'Instagram'
    | 'YouTube'
    | 'GitHub'
    | 'Discord'
    | 'TikTok'
    | 'Pinterest'
    | 'Snapchat'
    | 'WhatsApp'
    | 'Telegram'
    | 'Other';
  /**
   * Profile URL
   */
  url: string;
  /**
   * Custom label (optional, defaults to platform name)
   */
  label?: string | null;
  /**
   * Optional description for this social media account
   */
  description?: string | null;
  /**
   * Whether this social media link is active and should be displayed
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Unified collection for all page types including blogs, services, legal documents, and contact pages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Select the type of page you want to create. This determines which fields are available and how the page behaves on your website. Choose "Page" for general content, "Blog Post" for articles, "Service" for service descriptions, "Legal Document" for policies and terms, or "Contact Page" for contact forms and information.
   */
  pageType: 'page' | 'blog' | 'service' | 'legal' | 'contact';
  /**
   * The main title of the page (1-200 characters)
   */
  title: string;
  /**
   * Build your page layout using content blocks. Each block serves a specific purpose and can be customized with its own content and styling options.
   */
  layout?: (HeroBlock | CallToActionBlock | CodeBlock)[] | null;
  /**
   * Configuration specific to blog posts. These fields help organize and display your blog content effectively.
   */
  blogConfig?: {
    /**
     * Select the author of this blog post. If not specified, the current user will be automatically assigned as the author. Only administrators can change the author after creation.
     */
    author?: (number | null) | User;
    /**
     * Add tags to categorize this blog post. Tags help readers find related content and improve SEO. Each tag should be 1-50 characters long.
     */
    tags?:
      | {
          /**
           * A single tag for categorizing this blog post
           */
          tag: string;
          id?: string | null;
        }[]
      | null;
    /**
     * The date this blog post was first published. This will be automatically set when you publish the post for the first time. You can manually adjust it if needed.
     */
    publishedDate?: string | null;
    /**
     * A brief summary of the blog post content. This appears in blog listings, search results, and social media previews. Keep it engaging and informative (maximum 300 characters).
     */
    excerpt?: string | null;
  };
  /**
   * Configuration specific to service pages. These settings help showcase your services with pricing, categorization, and promotional features.
   */
  serviceConfig?: {
    /**
     * Set up pricing details for this service. This information will be displayed to potential clients and can be used for filtering and sorting services.
     */
    pricing?: {
      /**
       * The starting price for this service. Leave empty if pricing is custom or varies significantly.
       */
      amount?: number | null;
      /**
       * Select the currency for pricing display
       */
      currency?: ('USD' | 'EUR' | 'GBP' | 'INR') | null;
      /**
       * How is this service priced? Choose the model that best fits your service offering.
       */
      period?: ('fixed' | 'hourly' | 'monthly' | 'custom') | null;
    };
    /**
     * Categorize this service to help clients find what they need. This affects how the service appears in filtered lists and search results.
     */
    serviceType?: ('web-dev' | 'mobile-dev' | 'design' | 'consulting' | 'support' | 'marketing' | 'other') | null;
    /**
     * Mark this service as featured to highlight it on the homepage and in service listings. Only editors and administrators can set featured status.
     */
    featured?: boolean | null;
  };
  /**
   * Configuration specific to legal documents. These settings help manage compliance, versioning, and notifications for legal content.
   */
  legalConfig?: {
    /**
     * Select the type of legal document. This helps organize your legal content and may affect how the document is displayed or linked on your website.
     */
    documentType?: ('privacy' | 'terms' | 'cookies' | 'gdpr' | 'disclaimer' | 'license' | 'other') | null;
    /**
     * The date when this legal document becomes effective. This can be in the future for scheduled policy changes. Only editors and administrators can modify effective dates.
     */
    effectiveDate?: string | null;
    /**
     * The date this document was last modified. This is automatically updated whenever you save changes to the document.
     */
    lastUpdated?: string | null;
    /**
     * Send email notifications to specified recipients when this document is updated. Useful for compliance and stakeholder communication.
     */
    notifyOnChange?: boolean | null;
    /**
     * Email addresses that will receive notifications when this document is updated. Maximum 20 recipients allowed.
     */
    notificationRecipients?:
      | {
          /**
           * A valid email address for notifications
           */
          email: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Configuration specific to contact pages. These settings help organize contact forms and display appropriate contact information.
   */
  contactConfig?: {
    /**
     * Select the primary purpose of this contact page. This helps organize different types of inquiries and may affect form routing or display.
     */
    purpose:
      | 'general'
      | 'technical'
      | 'bug'
      | 'feature'
      | 'feedback'
      | 'sales'
      | 'partnership'
      | 'media'
      | 'careers'
      | 'custom';
    /**
     * Link contact forms to this page. These forms will be available for visitors to submit inquiries related to this contact page's purpose.
     */
    formRelations?:
      | {
          /**
           * Select a form to associate with this contact page
           */
          form: number | Form;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The URL-friendly identifier for this page (e.g., "about-us", "contact"). This is automatically generated from the title but can be customized. Must be unique and contain only letters, numbers, and hyphens. Maximum 100 characters.
   */
  slug?: string | null;
  /**
   * The complete URL path for this page, automatically generated based on the page hierarchy and type. This shows how the page will appear in the browser address bar.
   */
  url?: string | null;
  /**
   * Select a parent page to create a hierarchical structure (e.g., "About" > "Our Team"). This affects the URL structure and breadcrumb navigation. Leave empty for top-level pages.
   */
  parent?: (number | null) | Page;
  /**
   * Automatically generated breadcrumb trail showing the path from the homepage to this page. This is based on the page hierarchy and cannot be edited manually.
   */
  breadcrumbs?:
    | {
        doc?: (number | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * User who created this document (auto-populated)
   */
  createdBy?: (number | null) | User;
  /**
   * User who last updated this document (auto-populated)
   */
  updatedBy?: (number | null) | User;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Comma-separated keywords relevant to this content
     */
    keywords?: string | null;
    robots?: {
      /**
       * Check this to prevent search engines from indexing this page
       */
      noIndex?: boolean | null;
      /**
       * Check this to tell search engines not to follow links on this page
       */
      noFollow?: boolean | null;
      /**
       * Prevent search engines from showing cached versions of this page
       */
      noArchive?: boolean | null;
      /**
       * Prevent search engines from showing text snippets in search results
       */
      noSnippet?: boolean | null;
    };
    /**
     * The canonical URL for this page (leave empty to use the page URL)
     */
    canonical?: string | null;
    structured?: {
      /**
       * Select the most appropriate schema type for this content. Note: This field is auto-populated for specific collections (Blogs, Legal, Services, Contacts).
       */
      type?:
        | (
            | 'Article'
            | 'BlogPosting'
            | 'WebPage'
            | 'Organization'
            | 'Service'
            | 'LocalBusiness'
            | 'FAQPage'
            | 'ContactPage'
            | 'AboutPage'
            | 'custom'
          )
        | null;
      /**
       * Enter custom JSON-LD structured data
       */
      customSchema?: string | null;
      /**
       * Author of this content (for articles and blog posts)
       */
      author?: (number | null) | User;
      /**
       * Publication date (for articles and blog posts)
       */
      datePublished?: string | null;
      /**
       * Last modification date (for articles and blog posts)
       */
      dateModified?: string | null;
    };
    social?: {
      twitter?: {
        card?: ('summary' | 'summary_large_image' | 'app' | 'player') | null;
        /**
         * Twitter username for the website
         */
        site?: string | null;
        /**
         * Twitter username for the content creator
         */
        creator?: string | null;
      };
      facebook?: {
        /**
         * Facebook App ID for analytics
         */
        appId?: string | null;
      };
    };
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Choose the hero style variant
   */
  variant: 'default' | 'centered' | 'minimal' | 'split' | 'gradient' | 'codeTerminal';
  /**
   * Small text above the heading
   */
  eyebrow?: string | null;
  /**
   * Main heading text
   */
  heading: string;
  /**
   * Supporting text below the heading
   */
  subheading?: string | null;
  /**
   * Background image or media
   */
  media?: (number | null) | Media;
  /**
   * Video URL for background (MP4 format recommended)
   */
  videoUrl?: string | null;
  /**
   * Code snippet configuration for terminal variant
   */
  codeSnippet?: {
    language: 'javascript' | 'typescript' | 'python' | 'bash' | 'json';
    code: string;
    theme?: ('dark' | 'light') | null;
  };
  /**
   * Split layout configuration
   */
  splitLayout?: {
    /**
     * Which side should the text content appear on
     */
    contentSide: 'left' | 'right';
    /**
     * Type of media to display on the other side
     */
    mediaType: 'image' | 'video' | 'code';
  };
  /**
   * Gradient background configuration
   */
  gradientConfig?: {
    /**
     * Gradient colors (2-4 colors)
     */
    colors?:
      | {
          color: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Gradient animation style
     */
    animation?: ('wave' | 'pulse' | 'rotate') | null;
  };
  /**
   * Call-to-action buttons (max 3)
   */
  actions?:
    | {
        link: {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'secondary' | 'outline') | null;
          };
        };
        /**
         * Button style priority
         */
        priority?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  settings?: {
    /**
     * Text color theme (auto adapts to background)
     */
    theme?: ('light' | 'dark' | 'auto') | null;
    /**
     * Hero section height
     */
    height?: ('small' | 'medium' | 'large' | 'auto') | null;
    /**
     * Enable parallax scrolling effect for background
     */
    enableParallax?: boolean | null;
    overlay?: {
      /**
       * Add overlay to background media
       */
      enabled?: boolean | null;
      /**
       * Overlay opacity (0-100)
       */
      opacity?: number | null;
      /**
       * Overlay color
       */
      color?: ('black' | 'white' | 'primary') | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  /**
   * Choose the layout style for the call-to-action
   */
  variant?: ('centered' | 'split' | 'banner' | 'card') | null;
  /**
   * Main heading for the CTA
   */
  heading: string;
  /**
   * Optional description text
   */
  description?: string | null;
  /**
   * Optional rich text content for more complex CTAs
   */
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Optional background or side image
   */
  media?: (number | null) | Media;
  /**
   * Background color scheme
   */
  backgroundColor?: ('default' | 'primary' | 'dark' | 'light') | null;
  /**
   * Optional background pattern
   */
  pattern?: ('none' | 'dots' | 'grid' | 'waves') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  /**
   * Select the programming language for syntax highlighting
   */
  language:
    | 'typescript'
    | 'javascript'
    | 'python'
    | 'java'
    | 'csharp'
    | 'cpp'
    | 'c'
    | 'go'
    | 'rust'
    | 'php'
    | 'ruby'
    | 'swift'
    | 'kotlin'
    | 'html'
    | 'css'
    | 'scss'
    | 'json'
    | 'yaml'
    | 'markdown'
    | 'sql'
    | 'bash'
    | 'shell'
    | 'powershell'
    | 'graphql'
    | 'dockerfile';
  /**
   * Enter your code snippet
   */
  code: string;
  /**
   * Optional filename to display above the code block
   */
  filename?: string | null;
  /**
   * Display line numbers in the code block
   */
  showLineNumbers?: boolean | null;
  /**
   * Comma-separated line numbers to highlight (e.g., 1,3-5,7)
   */
  highlightLines?: string | null;
  /**
   * Color theme for the code block
   */
  theme?: ('auto' | 'dark' | 'light') | null;
  /**
   * Show copy-to-clipboard button
   */
  enableCopy?: boolean | null;
  /**
   * Optional caption to display below the code block
   */
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  emailNotifications?: {
    /**
     * Send email notifications when forms are submitted
     */
    enabled?: boolean | null;
    /**
     * Email addresses that will receive form submission notifications
     */
    recipients?:
      | {
          email: string;
          /**
           * Optional name for this recipient
           */
          name?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Subject line for notification emails
     */
    subject?: string | null;
    /**
     * Email address for replies (leave empty to use submitter email)
     */
    replyTo?: string | null;
    /**
     * Include form submission data in the notification email
     */
    includeSubmissionData?: boolean | null;
  };
  validationSettings?: {
    /**
     * Add hidden field to prevent spam bot submissions
     */
    enableHoneypot?: boolean | null;
    /**
     * Limit number of submissions per IP address
     */
    enableRateLimit?: boolean | null;
    /**
     * Time window for rate limiting (1-1440 minutes)
     */
    rateLimitWindow?: number | null;
    /**
     * Maximum number of submissions allowed per IP in the time window
     */
    maxSubmissionsPerWindow?: number | null;
    /**
     * Only allow authenticated users to submit this form
     */
    requireAuthentication?: boolean | null;
  };
  responseSettings?: {
    /**
     * Message shown after successful form submission
     */
    successMessage?: string | null;
    /**
     * Message shown when form submission fails
     */
    errorMessage?: string | null;
    /**
     * Optional URL to redirect to after successful submission
     */
    redirectUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analyticsData".
 */
export interface AnalyticsDatum {
  id: number;
  cacheKey?: string | null;
  cacheTimestamp?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'social-media';
        value: number | SocialMedia;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'analyticsData';
        value: number | AnalyticsDatum;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  roles?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  focalPoint?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-media_select".
 */
export interface SocialMediaSelect<T extends boolean = true> {
  platform?: T;
  url?: T;
  label?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  pageType?: T;
  title?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        code?: T | CodeBlockSelect<T>;
      };
  blogConfig?:
    | T
    | {
        author?: T;
        tags?:
          | T
          | {
              tag?: T;
              id?: T;
            };
        publishedDate?: T;
        excerpt?: T;
      };
  serviceConfig?:
    | T
    | {
        pricing?:
          | T
          | {
              amount?: T;
              currency?: T;
              period?: T;
            };
        serviceType?: T;
        featured?: T;
      };
  legalConfig?:
    | T
    | {
        documentType?: T;
        effectiveDate?: T;
        lastUpdated?: T;
        notifyOnChange?: T;
        notificationRecipients?:
          | T
          | {
              email?: T;
              id?: T;
            };
      };
  contactConfig?:
    | T
    | {
        purpose?: T;
        formRelations?:
          | T
          | {
              form?: T;
              id?: T;
            };
      };
  slug?: T;
  url?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
        robots?:
          | T
          | {
              noIndex?: T;
              noFollow?: T;
              noArchive?: T;
              noSnippet?: T;
            };
        canonical?: T;
        structured?:
          | T
          | {
              type?: T;
              customSchema?: T;
              author?: T;
              datePublished?: T;
              dateModified?: T;
            };
        social?:
          | T
          | {
              twitter?:
                | T
                | {
                    card?: T;
                    site?: T;
                    creator?: T;
                  };
              facebook?:
                | T
                | {
                    appId?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  media?: T;
  videoUrl?: T;
  codeSnippet?:
    | T
    | {
        language?: T;
        code?: T;
        theme?: T;
      };
  splitLayout?:
    | T
    | {
        contentSide?: T;
        mediaType?: T;
      };
  gradientConfig?:
    | T
    | {
        colors?:
          | T
          | {
              color?: T;
              id?: T;
            };
        animation?: T;
      };
  actions?:
    | T
    | {
        link?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
            };
        priority?: T;
        id?: T;
      };
  settings?:
    | T
    | {
        theme?: T;
        height?: T;
        enableParallax?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              opacity?: T;
              color?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  variant?: T;
  heading?: T;
  description?: T;
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  media?: T;
  backgroundColor?: T;
  pattern?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock_select".
 */
export interface CodeBlockSelect<T extends boolean = true> {
  language?: T;
  code?: T;
  filename?: T;
  showLineNumbers?: T;
  highlightLines?: T;
  theme?: T;
  enableCopy?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analyticsData_select".
 */
export interface AnalyticsDataSelect<T extends boolean = true> {
  cacheKey?: T;
  cacheTimestamp?: T;
  data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  emailNotifications?:
    | T
    | {
        enabled?: T;
        recipients?:
          | T
          | {
              email?: T;
              name?: T;
              id?: T;
            };
        subject?: T;
        replyTo?: T;
        includeSubmissionData?: T;
      };
  validationSettings?:
    | T
    | {
        enableHoneypot?: T;
        enableRateLimit?: T;
        rateLimitWindow?: T;
        maxSubmissionsPerWindow?: T;
        requireAuthentication?: T;
      };
  responseSettings?:
    | T
    | {
        successMessage?: T;
        errorMessage?: T;
        redirectUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configure the site header navigation and branding
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Main navigation menu items (maximum 8 items)
   */
  tabs?:
    | {
        /**
         * Navigation item label (max 50 characters)
         */
        label: string;
        /**
         * Enable direct navigation link
         */
        enableDirectLink?: boolean | null;
        /**
         * Enable dropdown submenu
         */
        enableDropdown?: boolean | null;
        /**
         * Configure direct navigation link
         */
        directLink?: {
          link?: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
          };
        };
        /**
         * Configure dropdown submenu
         */
        dropdown?: {
          /**
           * Optional description for the dropdown (max 200 characters)
           */
          description?: string | null;
          /**
           * Links within the dropdown description (max 3)
           */
          descriptionLinks?:
            | {
                link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?: {
                    relationTo: 'pages';
                    value: number | Page;
                  } | null;
                  url?: string | null;
                  label: string;
                };
                id?: string | null;
              }[]
            | null;
          /**
           * Dropdown navigation items (max 12)
           */
          navItems?:
            | {
                /**
                 * Visual style for this dropdown item
                 */
                style: 'default' | 'featured' | 'list';
                defaultLink?: {
                  link: {
                    type?: ('reference' | 'custom') | null;
                    newTab?: boolean | null;
                    reference?: {
                      relationTo: 'pages';
                      value: number | Page;
                    } | null;
                    url?: string | null;
                    label: string;
                  };
                  /**
                   * Optional description (max 100 characters)
                   */
                  description?: string | null;
                };
                featuredLink?: {
                  /**
                   * Featured tag (e.g., "New", "Popular") - max 20 characters
                   */
                  tag?: string | null;
                  /**
                   * Featured item label (max 50 characters)
                   */
                  label: string;
                  /**
                   * Featured links (max 5)
                   */
                  links?:
                    | {
                        link: {
                          type?: ('reference' | 'custom') | null;
                          newTab?: boolean | null;
                          reference?: {
                            relationTo: 'pages';
                            value: number | Page;
                          } | null;
                          url?: string | null;
                          label: string;
                        };
                        id?: string | null;
                      }[]
                    | null;
                };
                listLinks?: {
                  /**
                   * List section tag (max 20 characters)
                   */
                  tag?: string | null;
                  /**
                   * List links (max 8)
                   */
                  links?:
                    | {
                        link: {
                          type?: ('reference' | 'custom') | null;
                          newTab?: boolean | null;
                          reference?: {
                            relationTo: 'pages';
                            value: number | Page;
                          } | null;
                          url?: string | null;
                          label: string;
                        };
                        id?: string | null;
                      }[]
                    | null;
                };
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Header logo image (recommended: SVG or PNG with transparent background)
   */
  logo?: (number | null) | Media;
  /**
   * Alt text for the logo (required for accessibility)
   */
  logoAlt?: string | null;
  /**
   * Call-to-action button in the header
   */
  menuCta: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'secondary' | 'outline') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure the site footer navigation and content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Footer navigation columns (max 6 columns)
   */
  columns?:
    | {
        /**
         * Column heading (max 50 characters)
         */
        label: string;
        /**
         * Navigation links for this column (max 10)
         */
        navItems?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Copyright notice and legal text with enhanced formatting
   */
  copyright?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Legal and policy links (max 8)
   */
  legalLinks?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Select social media links to display in the footer
   */
  socialMedia?: {
    enabled?: boolean | null;
    /**
     * Select social media links from the global social media collection
     */
    links?: (number | SocialMedia)[] | null;
  };
  /**
   * Newsletter signup configuration
   */
  newsletter?: {
    enabled?: boolean | null;
    /**
     * Newsletter section title
     */
    title?: string | null;
    /**
     * Newsletter description text
     */
    description?: string | null;
    /**
     * Email input placeholder text
     */
    placeholder?: string | null;
    /**
     * Subscribe button text
     */
    buttonText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure global contact information and social media
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface ContactInformation {
  id: number;
  /**
   * Official company or organization name
   */
  companyName: string;
  /**
   * Company tagline or slogan
   */
  tagline?: string | null;
  /**
   * Main contact information displayed publicly
   */
  primaryContact: {
    /**
     * Primary contact email address
     */
    email: string;
    /**
     * Primary phone number
     */
    phone?: string | null;
    /**
     * Business address information
     */
    address?: {
      /**
       * Street address
       */
      street?: string | null;
      /**
       * City
       */
      city?: string | null;
      /**
       * State or province
       */
      state?: string | null;
      /**
       * Postal or ZIP code
       */
      postalCode?: string | null;
      /**
       * Country
       */
      country?: string | null;
    };
  };
  /**
   * Additional contact methods or departments (max 5)
   */
  additionalContacts?:
    | {
        /**
         * Contact label (e.g., "Sales", "Support", "Media")
         */
        label: string;
        /**
         * Contact email
         */
        email?: string | null;
        /**
         * Contact phone
         */
        phone?: string | null;
        /**
         * Brief description of this contact method
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Configure when your business is open
   */
  businessHours?: {
    /**
     * Show business hours on the website
     */
    enabled?: boolean | null;
    /**
     * Business timezone
     */
    timezone?:
      | (
          | 'America/New_York'
          | 'America/Chicago'
          | 'America/Denver'
          | 'America/Los_Angeles'
          | 'UTC'
          | 'Europe/London'
          | 'Europe/Paris'
        )
      | null;
    /**
     * Configure hours for each day of the week
     */
    schedule?:
      | {
          /**
           * Day of the week
           */
          day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
          /**
           * Is the business open on this day?
           */
          isOpen?: boolean | null;
          /**
           * Opening time (e.g., "9:00 AM")
           */
          openTime?: string | null;
          /**
           * Closing time (e.g., "5:00 PM")
           */
          closeTime?: string | null;
          /**
           * Optional note for this day (e.g., "Appointment only")
           */
          note?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Special hours for holidays or events (max 10)
     */
    specialHours?:
      | {
          /**
           * Date for special hours
           */
          date: string;
          /**
           * Label for this special day (e.g., "Christmas Day")
           */
          label: string;
          /**
           * Is the business closed on this day?
           */
          isClosed?: boolean | null;
          /**
           * Special opening time
           */
          openTime?: string | null;
          /**
           * Special closing time
           */
          closeTime?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  tabs?:
    | T
    | {
        label?: T;
        enableDirectLink?: T;
        enableDropdown?: T;
        directLink?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                  };
            };
        dropdown?:
          | T
          | {
              description?: T;
              descriptionLinks?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              navItems?:
                | T
                | {
                    style?: T;
                    defaultLink?:
                      | T
                      | {
                          link?:
                            | T
                            | {
                                type?: T;
                                newTab?: T;
                                reference?: T;
                                url?: T;
                                label?: T;
                              };
                          description?: T;
                        };
                    featuredLink?:
                      | T
                      | {
                          tag?: T;
                          label?: T;
                          links?:
                            | T
                            | {
                                link?:
                                  | T
                                  | {
                                      type?: T;
                                      newTab?: T;
                                      reference?: T;
                                      url?: T;
                                      label?: T;
                                    };
                                id?: T;
                              };
                        };
                    listLinks?:
                      | T
                      | {
                          tag?: T;
                          links?:
                            | T
                            | {
                                link?:
                                  | T
                                  | {
                                      type?: T;
                                      newTab?: T;
                                      reference?: T;
                                      url?: T;
                                      label?: T;
                                    };
                                id?: T;
                              };
                        };
                    id?: T;
                  };
            };
        id?: T;
      };
  logo?: T;
  logoAlt?: T;
  menuCta?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        label?: T;
        navItems?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  legalLinks?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  socialMedia?:
    | T
    | {
        enabled?: T;
        links?: T;
      };
  newsletter?:
    | T
    | {
        enabled?: T;
        title?: T;
        description?: T;
        placeholder?: T;
        buttonText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  companyName?: T;
  tagline?: T;
  primaryContact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?:
          | T
          | {
              street?: T;
              city?: T;
              state?: T;
              postalCode?: T;
              country?: T;
            };
      };
  additionalContacts?:
    | T
    | {
        label?: T;
        email?: T;
        phone?: T;
        description?: T;
        id?: T;
      };
  businessHours?:
    | T
    | {
        enabled?: T;
        timezone?: T;
        schedule?:
          | T
          | {
              day?: T;
              isOpen?: T;
              openTime?: T;
              closeTime?: T;
              note?: T;
              id?: T;
            };
        specialHours?:
          | T
          | {
              date?: T;
              label?: T;
              isClosed?: T;
              openTime?: T;
              closeTime?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}