/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    blogs: BlogPage;
    services: ServicePage;
    legal: LegalPage;
    contacts: ContactPage;
    analyticsData: AnalyticsDatum;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    legal: LegalSelect<false> | LegalSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    analyticsData: AnalyticsDataSelect<false> | AnalyticsDataSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    contact: Contact;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  roles: ('super-admin' | 'admin' | 'editor' | 'author' | 'user')[];
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text is required for accessibility compliance
   */
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Click to set the focal point for responsive cropping
   *
   * @minItems 2
   * @maxItems 2
   */
  focalPoint?: [number, number] | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Add an optional hero section at the top of your page. Leave empty for no hero.
   */
  hero?: HeroBlock[] | null;
  /**
   * The main title of the page
   */
  title: string;
  /**
   * Build your page layout using content blocks
   */
  layout?: (ContentBlock | CallToActionBlock | MediaBlock | ArchiveBlock | BannerBlock | CodeBlock)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Comma-separated keywords relevant to this content
     */
    keywords?: string | null;
    robots?: {
      /**
       * Check this to prevent search engines from indexing this page
       */
      noIndex?: boolean | null;
      /**
       * Check this to tell search engines not to follow links on this page
       */
      noFollow?: boolean | null;
      /**
       * Prevent search engines from showing cached versions of this page
       */
      noArchive?: boolean | null;
      /**
       * Prevent search engines from showing text snippets in search results
       */
      noSnippet?: boolean | null;
    };
    /**
     * The canonical URL for this page (leave empty to use the page URL)
     */
    canonical?: string | null;
    structured?: {
      /**
       * Select the most appropriate schema type for this content. Note: This field is auto-populated for specific collections (Blogs, Legal, Services, Contacts).
       */
      type?:
        | (
            | 'Article'
            | 'BlogPosting'
            | 'WebPage'
            | 'Organization'
            | 'Service'
            | 'LocalBusiness'
            | 'FAQPage'
            | 'ContactPage'
            | 'AboutPage'
            | 'custom'
          )
        | null;
      /**
       * Enter custom JSON-LD structured data
       */
      customSchema?: string | null;
      /**
       * Author of this content (for articles and blog posts)
       */
      author?: (number | null) | User;
      /**
       * Publication date (for articles and blog posts)
       */
      datePublished?: string | null;
      /**
       * Last modification date (for articles and blog posts)
       */
      dateModified?: string | null;
    };
    social?: {
      twitter?: {
        card?: ('summary' | 'summary_large_image' | 'app' | 'player') | null;
        /**
         * Twitter username for the website
         */
        site?: string | null;
        /**
         * Twitter username for the content creator
         */
        creator?: string | null;
      };
      facebook?: {
        /**
         * Facebook App ID for analytics
         */
        appId?: string | null;
      };
    };
  };
  /**
   * URL-friendly identifier (auto-generated from title)
   */
  slug?: string | null;
  /**
   * Select a parent page to create a hierarchical structure
   */
  parent?: (number | null) | Page;
  /**
   * Automatically generated breadcrumb trail based on page hierarchy
   */
  breadcrumbs?:
    | {
        doc?: (number | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Choose the hero style variant
   */
  variant: 'default' | 'centered' | 'minimal' | 'split' | 'gradient' | 'codeTerminal';
  /**
   * Small text above the heading
   */
  eyebrow?: string | null;
  /**
   * Main heading text
   */
  heading: string;
  /**
   * Supporting text below the heading
   */
  subheading?: string | null;
  /**
   * Background image or media
   */
  media?: (number | null) | Media;
  /**
   * Video URL for background (MP4 format recommended)
   */
  videoUrl?: string | null;
  /**
   * Code snippet configuration for terminal variant
   */
  codeSnippet?: {
    language: 'javascript' | 'typescript' | 'python' | 'bash' | 'json';
    code: string;
    theme?: ('dark' | 'light') | null;
  };
  /**
   * Split layout configuration
   */
  splitLayout?: {
    /**
     * Which side should the text content appear on
     */
    contentSide: 'left' | 'right';
    /**
     * Type of media to display on the other side
     */
    mediaType: 'image' | 'video' | 'code';
  };
  /**
   * Gradient background configuration
   */
  gradientConfig?: {
    /**
     * Gradient colors (2-4 colors)
     */
    colors?:
      | {
          color: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Gradient animation style
     */
    animation?: ('wave' | 'pulse' | 'rotate') | null;
  };
  /**
   * Call-to-action buttons (max 3)
   */
  actions?:
    | {
        link: {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'blogs';
                  value: number | BlogPage;
                } | null)
              | ({
                  relationTo: 'services';
                  value: number | ServicePage;
                } | null)
              | ({
                  relationTo: 'legal';
                  value: number | LegalPage;
                } | null)
              | ({
                  relationTo: 'contacts';
                  value: number | ContactPage;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'secondary' | 'outline') | null;
          };
        };
        /**
         * Button style priority
         */
        priority?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  settings?: {
    /**
     * Text color theme (auto adapts to background)
     */
    theme?: ('light' | 'dark' | 'auto') | null;
    /**
     * Hero section height
     */
    height?: ('small' | 'medium' | 'large' | 'auto') | null;
    /**
     * Enable parallax scrolling effect for background
     */
    enableParallax?: boolean | null;
    overlay?: {
      /**
       * Add overlay to background media
       */
      enabled?: boolean | null;
      /**
       * Overlay opacity (0-100)
       */
      opacity?: number | null;
      /**
       * Overlay color
       */
      color?: ('black' | 'white' | 'primary') | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface BlogPage {
  id: number;
  title: string;
  /**
   * Brief description of the blog post for previews and SEO
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Comma-separated keywords relevant to this content
     */
    keywords?: string | null;
    robots?: {
      /**
       * Check this to prevent search engines from indexing this page
       */
      noIndex?: boolean | null;
      /**
       * Check this to tell search engines not to follow links on this page
       */
      noFollow?: boolean | null;
      /**
       * Prevent search engines from showing cached versions of this page
       */
      noArchive?: boolean | null;
      /**
       * Prevent search engines from showing text snippets in search results
       */
      noSnippet?: boolean | null;
    };
    /**
     * The canonical URL for this page (leave empty to use the page URL)
     */
    canonical?: string | null;
    structured?: {
      /**
       * Select the most appropriate schema type for this content. Note: This field is auto-populated for specific collections (Blogs, Legal, Services, Contacts).
       */
      type?:
        | (
            | 'Article'
            | 'BlogPosting'
            | 'WebPage'
            | 'Organization'
            | 'Service'
            | 'LocalBusiness'
            | 'FAQPage'
            | 'ContactPage'
            | 'AboutPage'
            | 'custom'
          )
        | null;
      /**
       * Enter custom JSON-LD structured data
       */
      customSchema?: string | null;
      /**
       * Author of this content (for articles and blog posts)
       */
      author?: (number | null) | User;
      /**
       * Publication date (for articles and blog posts)
       */
      datePublished?: string | null;
      /**
       * Last modification date (for articles and blog posts)
       */
      dateModified?: string | null;
    };
    social?: {
      twitter?: {
        card?: ('summary' | 'summary_large_image' | 'app' | 'player') | null;
        /**
         * Twitter username for the website
         */
        site?: string | null;
        /**
         * Twitter username for the content creator
         */
        creator?: string | null;
      };
      facebook?: {
        /**
         * Facebook App ID for analytics
         */
        appId?: string | null;
      };
    };
  };
  /**
   * URL-friendly identifier (auto-generated from title)
   */
  slug?: string | null;
  publishedDate?: string | null;
  author?: (number | null) | User;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface ServicePage {
  id: number;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Comma-separated keywords relevant to this content
     */
    keywords?: string | null;
    robots?: {
      /**
       * Check this to prevent search engines from indexing this page
       */
      noIndex?: boolean | null;
      /**
       * Check this to tell search engines not to follow links on this page
       */
      noFollow?: boolean | null;
      /**
       * Prevent search engines from showing cached versions of this page
       */
      noArchive?: boolean | null;
      /**
       * Prevent search engines from showing text snippets in search results
       */
      noSnippet?: boolean | null;
    };
    /**
     * The canonical URL for this page (leave empty to use the page URL)
     */
    canonical?: string | null;
    structured?: {
      /**
       * Select the most appropriate schema type for this content. Note: This field is auto-populated for specific collections (Blogs, Legal, Services, Contacts).
       */
      type?:
        | (
            | 'Article'
            | 'BlogPosting'
            | 'WebPage'
            | 'Organization'
            | 'Service'
            | 'LocalBusiness'
            | 'FAQPage'
            | 'ContactPage'
            | 'AboutPage'
            | 'custom'
          )
        | null;
      /**
       * Enter custom JSON-LD structured data
       */
      customSchema?: string | null;
      /**
       * Author of this content (for articles and blog posts)
       */
      author?: (number | null) | User;
      /**
       * Publication date (for articles and blog posts)
       */
      datePublished?: string | null;
      /**
       * Last modification date (for articles and blog posts)
       */
      dateModified?: string | null;
    };
    social?: {
      twitter?: {
        card?: ('summary' | 'summary_large_image' | 'app' | 'player') | null;
        /**
         * Twitter username for the website
         */
        site?: string | null;
        /**
         * Twitter username for the content creator
         */
        creator?: string | null;
      };
      facebook?: {
        /**
         * Facebook App ID for analytics
         */
        appId?: string | null;
      };
    };
  };
  /**
   * URL-friendly identifier (auto-generated from title)
   */
  slug?: string | null;
  serviceType?: ('web-dev' | 'mobile-dev' | 'design' | 'consulting' | 'support' | 'marketing' | 'other') | null;
  /**
   * Feature this service on the homepage
   */
  featured?: boolean | null;
  pricing?: {
    /**
     * Starting price for this service
     */
    startingPrice?: number | null;
    currency?: ('USD' | 'EUR' | 'GBP' | 'INR') | null;
    pricingModel?: ('fixed' | 'hourly' | 'monthly' | 'custom') | null;
  };
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal".
 */
export interface LegalPage {
  id: number;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Comma-separated keywords relevant to this content
     */
    keywords?: string | null;
    robots?: {
      /**
       * Check this to prevent search engines from indexing this page
       */
      noIndex?: boolean | null;
      /**
       * Check this to tell search engines not to follow links on this page
       */
      noFollow?: boolean | null;
      /**
       * Prevent search engines from showing cached versions of this page
       */
      noArchive?: boolean | null;
      /**
       * Prevent search engines from showing text snippets in search results
       */
      noSnippet?: boolean | null;
    };
    /**
     * The canonical URL for this page (leave empty to use the page URL)
     */
    canonical?: string | null;
    structured?: {
      /**
       * Select the most appropriate schema type for this content. Note: This field is auto-populated for specific collections (Blogs, Legal, Services, Contacts).
       */
      type?:
        | (
            | 'Article'
            | 'BlogPosting'
            | 'WebPage'
            | 'Organization'
            | 'Service'
            | 'LocalBusiness'
            | 'FAQPage'
            | 'ContactPage'
            | 'AboutPage'
            | 'custom'
          )
        | null;
      /**
       * Enter custom JSON-LD structured data
       */
      customSchema?: string | null;
      /**
       * Author of this content (for articles and blog posts)
       */
      author?: (number | null) | User;
      /**
       * Publication date (for articles and blog posts)
       */
      datePublished?: string | null;
      /**
       * Last modification date (for articles and blog posts)
       */
      dateModified?: string | null;
    };
    social?: {
      twitter?: {
        card?: ('summary' | 'summary_large_image' | 'app' | 'player') | null;
        /**
         * Twitter username for the website
         */
        site?: string | null;
        /**
         * Twitter username for the content creator
         */
        creator?: string | null;
      };
      facebook?: {
        /**
         * Facebook App ID for analytics
         */
        appId?: string | null;
      };
    };
  };
  /**
   * URL-friendly identifier (auto-generated from title)
   */
  slug?: string | null;
  documentType?: ('privacy' | 'terms' | 'cookies' | 'gdpr' | 'disclaimer' | 'license' | 'other') | null;
  /**
   * When this legal document becomes effective
   */
  effectiveDate?: string | null;
  /**
   * Last modification date of this document
   */
  lastUpdated?: string | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface ContactPage {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  purpose:
    | 'general'
    | 'technical'
    | 'bug'
    | 'feature'
    | 'feedback'
    | 'sales'
    | 'partnership'
    | 'media'
    | 'careers'
    | 'custom';
  form?: (number | null) | Form;
  displayContactInfo?: boolean | null;
  showFormAboveContent?: boolean | null;
  contactInfoSections?: ('general' | 'offices' | 'social' | 'hours')[] | null;
  sidebar?: {
    enableSidebar?: boolean | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Comma-separated keywords relevant to this content
     */
    keywords?: string | null;
    robots?: {
      /**
       * Check this to prevent search engines from indexing this page
       */
      noIndex?: boolean | null;
      /**
       * Check this to tell search engines not to follow links on this page
       */
      noFollow?: boolean | null;
      /**
       * Prevent search engines from showing cached versions of this page
       */
      noArchive?: boolean | null;
      /**
       * Prevent search engines from showing text snippets in search results
       */
      noSnippet?: boolean | null;
    };
    /**
     * The canonical URL for this page (leave empty to use the page URL)
     */
    canonical?: string | null;
    structured?: {
      /**
       * Select the most appropriate schema type for this content. Note: This field is auto-populated for specific collections (Blogs, Legal, Services, Contacts).
       */
      type?:
        | (
            | 'Article'
            | 'BlogPosting'
            | 'WebPage'
            | 'Organization'
            | 'Service'
            | 'LocalBusiness'
            | 'FAQPage'
            | 'ContactPage'
            | 'AboutPage'
            | 'custom'
          )
        | null;
      /**
       * Enter custom JSON-LD structured data
       */
      customSchema?: string | null;
      /**
       * Author of this content (for articles and blog posts)
       */
      author?: (number | null) | User;
      /**
       * Publication date (for articles and blog posts)
       */
      datePublished?: string | null;
      /**
       * Last modification date (for articles and blog posts)
       */
      dateModified?: string | null;
    };
    social?: {
      twitter?: {
        card?: ('summary' | 'summary_large_image' | 'app' | 'player') | null;
        /**
         * Twitter username for the website
         */
        site?: string | null;
        /**
         * Twitter username for the content creator
         */
        creator?: string | null;
      };
      facebook?: {
        /**
         * Facebook App ID for analytics
         */
        appId?: string | null;
      };
    };
  };
  /**
   * URL-friendly identifier (auto-generated from title)
   */
  slug?: string | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  emailNotifications?: {
    /**
     * Send email notifications when forms are submitted
     */
    enabled?: boolean | null;
    /**
     * Email addresses that will receive form submission notifications
     */
    recipients?:
      | {
          email: string;
          /**
           * Optional name for this recipient
           */
          name?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Subject line for notification emails
     */
    subject?: string | null;
    /**
     * Email address for replies (leave empty to use submitter email)
     */
    replyTo?: string | null;
    /**
     * Include form submission data in the notification email
     */
    includeSubmissionData?: boolean | null;
  };
  validationSettings?: {
    /**
     * Add hidden field to prevent spam bot submissions
     */
    enableHoneypot?: boolean | null;
    /**
     * Limit number of submissions per IP address
     */
    enableRateLimit?: boolean | null;
    /**
     * Time window for rate limiting (1-1440 minutes)
     */
    rateLimitWindow?: number | null;
    /**
     * Maximum number of submissions allowed per IP in the time window
     */
    maxSubmissionsPerWindow?: number | null;
    /**
     * Only allow authenticated users to submit this form
     */
    requireAuthentication?: boolean | null;
  };
  responseSettings?: {
    /**
     * Message shown after successful form submission
     */
    successMessage?: string | null;
    /**
     * Message shown when form submission fails
     */
    errorMessage?: string | null;
    /**
     * Optional URL to redirect to after successful submission
     */
    redirectUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size: 'oneThird' | 'half' | 'twoThirds' | 'full';
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'blogs';
                value: number | BlogPage;
              } | null)
            | ({
                relationTo: 'services';
                value: number | ServicePage;
              } | null)
            | ({
                relationTo: 'legal';
                value: number | LegalPage;
              } | null)
            | ({
                relationTo: 'contacts';
                value: number | ContactPage;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'secondary' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'blogs';
                value: number | BlogPage;
              } | null)
            | ({
                relationTo: 'services';
                value: number | ServicePage;
              } | null)
            | ({
                relationTo: 'legal';
                value: number | LegalPage;
              } | null)
            | ({
                relationTo: 'contacts';
                value: number | ContactPage;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy: 'collection' | 'selection';
  relationTo?: ('blogs' | 'services') | null;
  selectedDocs?:
    | (
        | {
            relationTo: 'blogs';
            value: number | BlogPage;
          }
        | {
            relationTo: 'services';
            value: number | ServicePage;
          }
      )[]
    | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analyticsData".
 */
export interface AnalyticsDatum {
  id: number;
  cacheKey?: string | null;
  cacheTimestamp?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | BlogPage;
      } | null)
    | ({
        relationTo: 'services';
        value: number | ServicePage;
      } | null)
    | ({
        relationTo: 'legal';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'contacts';
        value: number | ContactPage;
      } | null)
    | ({
        relationTo: 'analyticsData';
        value: number | AnalyticsDatum;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  roles?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  focalPoint?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
      };
  title?: T;
  layout?:
    | T
    | {
        content?: T | ContentBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        code?: T | CodeBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
        robots?:
          | T
          | {
              noIndex?: T;
              noFollow?: T;
              noArchive?: T;
              noSnippet?: T;
            };
        canonical?: T;
        structured?:
          | T
          | {
              type?: T;
              customSchema?: T;
              author?: T;
              datePublished?: T;
              dateModified?: T;
            };
        social?:
          | T
          | {
              twitter?:
                | T
                | {
                    card?: T;
                    site?: T;
                    creator?: T;
                  };
              facebook?:
                | T
                | {
                    appId?: T;
                  };
            };
      };
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  media?: T;
  videoUrl?: T;
  codeSnippet?:
    | T
    | {
        language?: T;
        code?: T;
        theme?: T;
      };
  splitLayout?:
    | T
    | {
        contentSide?: T;
        mediaType?: T;
      };
  gradientConfig?:
    | T
    | {
        colors?:
          | T
          | {
              color?: T;
              id?: T;
            };
        animation?: T;
      };
  actions?:
    | T
    | {
        link?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
            };
        priority?: T;
        id?: T;
      };
  settings?:
    | T
    | {
        theme?: T;
        height?: T;
        enableParallax?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              opacity?: T;
              color?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  selectedDocs?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock_select".
 */
export interface CodeBlockSelect<T extends boolean = true> {
  language?: T;
  code?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
        robots?:
          | T
          | {
              noIndex?: T;
              noFollow?: T;
              noArchive?: T;
              noSnippet?: T;
            };
        canonical?: T;
        structured?:
          | T
          | {
              type?: T;
              customSchema?: T;
              author?: T;
              datePublished?: T;
              dateModified?: T;
            };
        social?:
          | T
          | {
              twitter?:
                | T
                | {
                    card?: T;
                    site?: T;
                    creator?: T;
                  };
              facebook?:
                | T
                | {
                    appId?: T;
                  };
            };
      };
  slug?: T;
  publishedDate?: T;
  author?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
        robots?:
          | T
          | {
              noIndex?: T;
              noFollow?: T;
              noArchive?: T;
              noSnippet?: T;
            };
        canonical?: T;
        structured?:
          | T
          | {
              type?: T;
              customSchema?: T;
              author?: T;
              datePublished?: T;
              dateModified?: T;
            };
        social?:
          | T
          | {
              twitter?:
                | T
                | {
                    card?: T;
                    site?: T;
                    creator?: T;
                  };
              facebook?:
                | T
                | {
                    appId?: T;
                  };
            };
      };
  slug?: T;
  serviceType?: T;
  featured?: T;
  pricing?:
    | T
    | {
        startingPrice?: T;
        currency?: T;
        pricingModel?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal_select".
 */
export interface LegalSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
        robots?:
          | T
          | {
              noIndex?: T;
              noFollow?: T;
              noArchive?: T;
              noSnippet?: T;
            };
        canonical?: T;
        structured?:
          | T
          | {
              type?: T;
              customSchema?: T;
              author?: T;
              datePublished?: T;
              dateModified?: T;
            };
        social?:
          | T
          | {
              twitter?:
                | T
                | {
                    card?: T;
                    site?: T;
                    creator?: T;
                  };
              facebook?:
                | T
                | {
                    appId?: T;
                  };
            };
      };
  slug?: T;
  documentType?: T;
  effectiveDate?: T;
  lastUpdated?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  purpose?: T;
  form?: T;
  displayContactInfo?: T;
  showFormAboveContent?: T;
  contactInfoSections?: T;
  sidebar?:
    | T
    | {
        enableSidebar?: T;
        content?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
        robots?:
          | T
          | {
              noIndex?: T;
              noFollow?: T;
              noArchive?: T;
              noSnippet?: T;
            };
        canonical?: T;
        structured?:
          | T
          | {
              type?: T;
              customSchema?: T;
              author?: T;
              datePublished?: T;
              dateModified?: T;
            };
        social?:
          | T
          | {
              twitter?:
                | T
                | {
                    card?: T;
                    site?: T;
                    creator?: T;
                  };
              facebook?:
                | T
                | {
                    appId?: T;
                  };
            };
      };
  slug?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analyticsData_select".
 */
export interface AnalyticsDataSelect<T extends boolean = true> {
  cacheKey?: T;
  cacheTimestamp?: T;
  data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  emailNotifications?:
    | T
    | {
        enabled?: T;
        recipients?:
          | T
          | {
              email?: T;
              name?: T;
              id?: T;
            };
        subject?: T;
        replyTo?: T;
        includeSubmissionData?: T;
      };
  validationSettings?:
    | T
    | {
        enableHoneypot?: T;
        enableRateLimit?: T;
        rateLimitWindow?: T;
        maxSubmissionsPerWindow?: T;
        requireAuthentication?: T;
      };
  responseSettings?:
    | T
    | {
        successMessage?: T;
        errorMessage?: T;
        redirectUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  tabs?:
    | {
        label: string;
        enableDirectLink?: boolean | null;
        enableDropdown?: boolean | null;
        directLink?: {
          link?: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'blogs';
                  value: number | BlogPage;
                } | null)
              | ({
                  relationTo: 'services';
                  value: number | ServicePage;
                } | null)
              | ({
                  relationTo: 'legal';
                  value: number | LegalPage;
                } | null)
              | ({
                  relationTo: 'contacts';
                  value: number | ContactPage;
                } | null);
            url?: string | null;
          };
        };
        dropdown?: {
          description?: string | null;
          descriptionLinks?:
            | {
                link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: number | Page;
                      } | null)
                    | ({
                        relationTo: 'blogs';
                        value: number | BlogPage;
                      } | null)
                    | ({
                        relationTo: 'services';
                        value: number | ServicePage;
                      } | null)
                    | ({
                        relationTo: 'legal';
                        value: number | LegalPage;
                      } | null)
                    | ({
                        relationTo: 'contacts';
                        value: number | ContactPage;
                      } | null);
                  url?: string | null;
                  label: string;
                };
                id?: string | null;
              }[]
            | null;
          navItems?:
            | {
                style?: ('default' | 'featured' | 'list') | null;
                defaultLink?: {
                  link: {
                    type?: ('reference' | 'custom') | null;
                    newTab?: boolean | null;
                    reference?:
                      | ({
                          relationTo: 'pages';
                          value: number | Page;
                        } | null)
                      | ({
                          relationTo: 'blogs';
                          value: number | BlogPage;
                        } | null)
                      | ({
                          relationTo: 'services';
                          value: number | ServicePage;
                        } | null)
                      | ({
                          relationTo: 'legal';
                          value: number | LegalPage;
                        } | null)
                      | ({
                          relationTo: 'contacts';
                          value: number | ContactPage;
                        } | null);
                    url?: string | null;
                    label: string;
                  };
                  description?: string | null;
                };
                featuredLink?: {
                  tag?: string | null;
                  label?: string | null;
                  links?:
                    | {
                        link: {
                          type?: ('reference' | 'custom') | null;
                          newTab?: boolean | null;
                          reference?:
                            | ({
                                relationTo: 'pages';
                                value: number | Page;
                              } | null)
                            | ({
                                relationTo: 'blogs';
                                value: number | BlogPage;
                              } | null)
                            | ({
                                relationTo: 'services';
                                value: number | ServicePage;
                              } | null)
                            | ({
                                relationTo: 'legal';
                                value: number | LegalPage;
                              } | null)
                            | ({
                                relationTo: 'contacts';
                                value: number | ContactPage;
                              } | null);
                          url?: string | null;
                          label: string;
                        };
                        id?: string | null;
                      }[]
                    | null;
                };
                listLinks?: {
                  tag?: string | null;
                  links?:
                    | {
                        link: {
                          type?: ('reference' | 'custom') | null;
                          newTab?: boolean | null;
                          reference?:
                            | ({
                                relationTo: 'pages';
                                value: number | Page;
                              } | null)
                            | ({
                                relationTo: 'blogs';
                                value: number | BlogPage;
                              } | null)
                            | ({
                                relationTo: 'services';
                                value: number | ServicePage;
                              } | null)
                            | ({
                                relationTo: 'legal';
                                value: number | LegalPage;
                              } | null)
                            | ({
                                relationTo: 'contacts';
                                value: number | ContactPage;
                              } | null);
                          url?: string | null;
                          label: string;
                        };
                        id?: string | null;
                      }[]
                    | null;
                };
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
      }[]
    | null;
  menuCta: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'blogs';
          value: number | BlogPage;
        } | null)
      | ({
          relationTo: 'services';
          value: number | ServicePage;
        } | null)
      | ({
          relationTo: 'legal';
          value: number | LegalPage;
        } | null)
      | ({
          relationTo: 'contacts';
          value: number | ContactPage;
        } | null);
    url?: string | null;
    label: string;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Comma-separated keywords relevant to this content
     */
    keywords?: string | null;
    robots?: {
      /**
       * Check this to prevent search engines from indexing this page
       */
      noIndex?: boolean | null;
      /**
       * Check this to tell search engines not to follow links on this page
       */
      noFollow?: boolean | null;
      /**
       * Prevent search engines from showing cached versions of this page
       */
      noArchive?: boolean | null;
      /**
       * Prevent search engines from showing text snippets in search results
       */
      noSnippet?: boolean | null;
    };
    /**
     * The canonical URL for this page (leave empty to use the page URL)
     */
    canonical?: string | null;
    structured?: {
      /**
       * Select the most appropriate schema type for this content. Note: This field is auto-populated for specific collections (Blogs, Legal, Services, Contacts).
       */
      type?:
        | (
            | 'Article'
            | 'BlogPosting'
            | 'WebPage'
            | 'Organization'
            | 'Service'
            | 'LocalBusiness'
            | 'FAQPage'
            | 'ContactPage'
            | 'AboutPage'
            | 'custom'
          )
        | null;
      /**
       * Enter custom JSON-LD structured data
       */
      customSchema?: string | null;
      /**
       * Author of this content (for articles and blog posts)
       */
      author?: (number | null) | User;
      /**
       * Publication date (for articles and blog posts)
       */
      datePublished?: string | null;
      /**
       * Last modification date (for articles and blog posts)
       */
      dateModified?: string | null;
    };
    social?: {
      twitter?: {
        card?: ('summary' | 'summary_large_image' | 'app' | 'player') | null;
        /**
         * Twitter username for the website
         */
        site?: string | null;
        /**
         * Twitter username for the content creator
         */
        creator?: string | null;
      };
      facebook?: {
        /**
         * Facebook App ID for analytics
         */
        appId?: string | null;
      };
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        label: string;
        navItems?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'blogs';
                      value: number | BlogPage;
                    } | null)
                  | ({
                      relationTo: 'services';
                      value: number | ServicePage;
                    } | null)
                  | ({
                      relationTo: 'legal';
                      value: number | LegalPage;
                    } | null)
                  | ({
                      relationTo: 'contacts';
                      value: number | ContactPage;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Comma-separated keywords relevant to this content
     */
    keywords?: string | null;
    robots?: {
      /**
       * Check this to prevent search engines from indexing this page
       */
      noIndex?: boolean | null;
      /**
       * Check this to tell search engines not to follow links on this page
       */
      noFollow?: boolean | null;
      /**
       * Prevent search engines from showing cached versions of this page
       */
      noArchive?: boolean | null;
      /**
       * Prevent search engines from showing text snippets in search results
       */
      noSnippet?: boolean | null;
    };
    /**
     * The canonical URL for this page (leave empty to use the page URL)
     */
    canonical?: string | null;
    structured?: {
      /**
       * Select the most appropriate schema type for this content. Note: This field is auto-populated for specific collections (Blogs, Legal, Services, Contacts).
       */
      type?:
        | (
            | 'Article'
            | 'BlogPosting'
            | 'WebPage'
            | 'Organization'
            | 'Service'
            | 'LocalBusiness'
            | 'FAQPage'
            | 'ContactPage'
            | 'AboutPage'
            | 'custom'
          )
        | null;
      /**
       * Enter custom JSON-LD structured data
       */
      customSchema?: string | null;
      /**
       * Author of this content (for articles and blog posts)
       */
      author?: (number | null) | User;
      /**
       * Publication date (for articles and blog posts)
       */
      datePublished?: string | null;
      /**
       * Last modification date (for articles and blog posts)
       */
      dateModified?: string | null;
    };
    social?: {
      twitter?: {
        card?: ('summary' | 'summary_large_image' | 'app' | 'player') | null;
        /**
         * Twitter username for the website
         */
        site?: string | null;
        /**
         * Twitter username for the content creator
         */
        creator?: string | null;
      };
      facebook?: {
        /**
         * Facebook App ID for analytics
         */
        appId?: string | null;
      };
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  socialMedia?: {
    links?:
      | {
          platform: 'facebook' | 'twitter' | 'linkedin' | 'instagram' | 'youtube' | 'github';
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  tabs?:
    | T
    | {
        label?: T;
        enableDirectLink?: T;
        enableDropdown?: T;
        directLink?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                  };
            };
        dropdown?:
          | T
          | {
              description?: T;
              descriptionLinks?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              navItems?:
                | T
                | {
                    style?: T;
                    defaultLink?:
                      | T
                      | {
                          link?:
                            | T
                            | {
                                type?: T;
                                newTab?: T;
                                reference?: T;
                                url?: T;
                                label?: T;
                              };
                          description?: T;
                        };
                    featuredLink?:
                      | T
                      | {
                          tag?: T;
                          label?: T;
                          links?:
                            | T
                            | {
                                link?:
                                  | T
                                  | {
                                      type?: T;
                                      newTab?: T;
                                      reference?: T;
                                      url?: T;
                                      label?: T;
                                    };
                                id?: T;
                              };
                        };
                    listLinks?:
                      | T
                      | {
                          tag?: T;
                          links?:
                            | T
                            | {
                                link?:
                                  | T
                                  | {
                                      type?: T;
                                      newTab?: T;
                                      reference?: T;
                                      url?: T;
                                      label?: T;
                                    };
                                id?: T;
                              };
                        };
                    id?: T;
                  };
            };
        id?: T;
      };
  menuCta?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
        robots?:
          | T
          | {
              noIndex?: T;
              noFollow?: T;
              noArchive?: T;
              noSnippet?: T;
            };
        canonical?: T;
        structured?:
          | T
          | {
              type?: T;
              customSchema?: T;
              author?: T;
              datePublished?: T;
              dateModified?: T;
            };
        social?:
          | T
          | {
              twitter?:
                | T
                | {
                    card?: T;
                    site?: T;
                    creator?: T;
                  };
              facebook?:
                | T
                | {
                    appId?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        label?: T;
        navItems?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
        robots?:
          | T
          | {
              noIndex?: T;
              noFollow?: T;
              noArchive?: T;
              noSnippet?: T;
            };
        canonical?: T;
        structured?:
          | T
          | {
              type?: T;
              customSchema?: T;
              author?: T;
              datePublished?: T;
              dateModified?: T;
            };
        social?:
          | T
          | {
              twitter?:
                | T
                | {
                    card?: T;
                    site?: T;
                    creator?: T;
                  };
              facebook?:
                | T
                | {
                    appId?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  socialMedia?:
    | T
    | {
        links?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'blogs';
          value: number | BlogPage;
        } | null)
      | ({
          relationTo: 'services';
          value: number | ServicePage;
        } | null)
      | ({
          relationTo: 'legal';
          value: number | LegalPage;
        } | null)
      | ({
          relationTo: 'contacts';
          value: number | ContactPage;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}